fix flags for tracing & warnings
krojew/cdrs-tokio pull request #118
Opened 2022-10-10 17:19 UTC by conorbros

Finish implementing flags and their appropriate handling in the codec methods

2022-10-10 22:59 UTC, rukai commented
What about moving Flags::CUSTOM_PAYLOAD and Flags::BETA to be bool fields on the frame and then generating the flags at encode time?

As is, this PR has an important fix though, so lets not block on that.

2022-10-11 07:25 UTC, krojew requested changes
This change will break compression for v4 - the whole envelope body is expected to be compressed, rather than consisting of several compressed parts.

2022-10-11 07:25 UTC, krojew commented on cassandra-protocol/src/frame.rs
> +                .expect("Tracing flag was set but Envelope has no tracing_id")
We cannot crash on invalid data.

2022-10-12 08:29 UTC, krojew requested changes
Generally, looks good, but I'm concerned about the number of expensive allocations in such critical part. The typical case is encoding envelopes without tracing or warnings. In such situations the current implementation copies the whole envelope to a buffer as is, which is then copied to the output with optional compression. We have an unnecessary allocation + copy which can hurt performance.

2022-10-12 08:29 UTC, krojew commented on cassandra-protocol/src/frame.rs
> +            let encoded_body = compressor.encode(&body_buffer)?;
We can reuse body_buffer here to avoid eating twice the memory.

2022-10-13 06:46 UTC, conorbros commented
Most recent commit addresses those concerns. In the typical case (no flags) we can avoid having to concatenate the buffers.

2022-10-13 07:20 UTC, krojew requested changes

2022-10-13 07:20 UTC, krojew commented on cassandra-protocol/src/frame.rs
> +                warnings_buffer.extend_from_slice(&warning_len.to_be_bytes());
You can append to flags_buffer directly, thus avoiding a temporary buffer.

2022-10-13 07:20 UTC, krojew commented on cassandra-protocol/src/frame.rs
> +                compressor.encode(&[flags_buffer.as_slice(), &self.body].concat())?
`concat` should not be used as it creates a temporary vector and copies all the slices into it.

2022-10-13 07:20 UTC, krojew commented on cassandra-protocol/src/frame.rs
> +                v.extend_from_slice(&[flags_buffer.as_slice(), &self.body].concat());
As above.

2022-10-13 09:07 UTC, krojew commented
Thanks!

2022-10-13 09:07 UTC, merged