fix Compression to_string and into string impls
krojew/cdrs-tokio pull request #175
Opened 2024-01-19 05:07 UTC by conorbros

2024-01-19 06:04 UTC, krojew requested changes
Why is this needed?

2024-01-19 06:04 UTC, krojew commented on cassandra-protocol/src/compression.rs
> +    /// It converts `Compression` into `String`. If compression is `None` then empty string will be
It will be NONE, not empty.

2024-01-19 06:04 UTC, krojew commented on cassandra-protocol/src/compression.rs
> +            Compression::None => write!(fmt, "none"),
This is inconsistent with the implementation above.

2024-02-04 23:51 UTC, conorbros commented
I proposed this change so that the `to_string` function for the `Compression` enum formats it correctly according to the protocol spec. It should be either all caps or lowercase. The default impl will format it as the enum name e.g. `"Snappy"`, when it should be `"snappy"` or `"SNAPPY"`.

2024-02-05 11:10 UTC, krojew commented
In Rust typically string representations of enums reflect the names itself. I think it would be better to explicitly add `to_protocol_string()`/`from_protocol_string()` or similar.

2024-02-12 06:59 UTC, krojew requested changes

2024-02-12 06:59 UTC, krojew commented on cassandra-protocol/src/compression.rs
> +#[derive(Debug, PartialEq, Clone, Copy, Eq, Ord, PartialOrd, Hash)]
You forgot to put back Display.

2024-02-13 07:10 UTC, krojew approved these changes

2024-02-13 07:10 UTC, merged